# Multinomial covariate prediction in LUAD
_Last modified `r format(Sys.time(), "%I:%M %p on %b %d, %Y")`. This document, R session image, version history, knitr cache, figures, and other associated datasets are located in `/inside/grotto/blin/trna-markers/luad/predict/`._

```{r setup, echo=FALSE, warning=FALSE, results=FALSE, message=FALSE, errors=FALSE, cache=FALSE}
library(knitr)
opts_chunk$set(cache = TRUE, cache.path = "/inside/grotto/blin/trna-markers/luad/predict/cache/predict-multinomial/", eval = TRUE, echo = TRUE, warning = FALSE, results = FALSE, message = FALSE, autodep = TRUE, dev = "png", dpi = 300)
```

```{r libraries, cache=FALSE}
library(plyr)
library(glmnet)
library(ROCR)
library(GenomicRanges)
library(stringr)
library(reshape2)
library(caret)
set.seed(12)
source('predict.R')
load('/inside/home/blin/grotto/data/hg19-srnas.RData')
load('/inside/home/blin/grotto/trna-markers/process-reads/luad-counts.RData')
luad_clinical <- luad_clinical[match(colnames(luad_adjusted_counts), luad_clinical$barcode), ]
ntrials <- 150
tsrnas <- unique(srnas[srnas$class %in% c("fivehalf", "threehalf", "trailer")]$tx_name)
#tsrnas <- unique(srnas[srnas$class %in% c("fivehalf", "threehalf", "trailer")]$tx_name)
mirnas <- unique(srnas[str_detect(srnas$class, "mi")]$tx_name)
snornas <- unique(srnas[srnas$class == "snoRNA"]$tx_name)
```

```{r multinomial-function}
buildMultinomialGlm <- function(metadata, counts, covariate, features, randomize = FALSE) {
  # set up training/testing sets. first, set parameters
  dataset <- setupTrainingTestingSets(metadata, covariate, counts)
  training_counts <- t(dataset$training_counts[rownames(dataset$training_counts) %in% features, ])
  training_response <- dataset$training_metadata[match(colnames(dataset$training_counts), dataset$training_metadata$barcode), ][, covariate]
  testing_counts <- t(dataset$testing_counts[rownames(dataset$testing_counts) %in% features, ])
  testing_response <- dataset$testing_metadata[match(colnames(dataset$testing_counts), dataset$testing_metadata$barcode), ][, covariate]
  if (randomize) training_response <- sample(training_response)

  # build and test model
  model <- cv.glmnet(training_counts, training_response, family = "multinomial", type.measure = "class", type.multinomial = "grouped")
  pred <- predict(model, newx = testing_counts, s = "lambda.min", type = "class") 
  unname(confusionMatrix(pred, testing_response)$overall[1])
}
```

```{r predict-age}
metadata <- na.omit(luad_clinical[luad_clinical$sample_type == "TP", ])
metadata$age <- cut(as.integer(as.character(metadata$age)), breaks = c(0, 60, 75, 100), labels = c("<60", "60-75", "75+"))
counts <- luad_adjusted_counts[, colnames(luad_adjusted_counts) %in% metadata$barcode]
mirna_age_acc <- sapply(1:ntrials, function(i) buildMultinomialGlm(metadata, counts, "age", mirnas))
tsrna_age_acc <- sapply(1:ntrials, function(i) buildMultinomialGlm(metadata, counts, "age", tsrnas))
snorna_age_acc <- sapply(1:ntrials, function(i) buildMultinomialGlm(metadata, counts, "age", mirnas))
permuted_age_acc <- sapply(1:ntrials, function(i) buildMultinomialGlm(metadata, counts, "age", tsrnas, randomize = TRUE)) 
```

```{r plot-age-accuracy, fig.width=8, fig.height=5}
df <- data.frame(tsRNA = tsrna_age_acc, miRNA = mirna_age_acc, snoRNA = snorna_age_acc, Permuted = permuted_age_acc)
df <- melt(df)
colnames(df) <- c("Features", "Accuracy")
ggplot(df) + geom_boxplot(aes(x = Features, y = Accuracy, color = Features))
```

## Predict subtype with GLMs

Lung adenocarcinoma comes in three main subtypes: PI, PP, and TRU. 

```{r subtype-accuracy}
# load cluster information
load('/inside/grotto/blin/trna-markers/luad/cluster-subtypes/clusters.RData')
clusters <- clusters[clusters$known, ]
metadata <- luad_clinical[substr(luad_clinical$barcode, 1, 12) %in% clusters$barcode & luad_clinical$sample_type == "TP", ]
metadata$subtype <- as.factor(clusters$subtype[match(substr(metadata$barcode, 1, 12), clusters$barcode)])

counts <- luad_adjusted_counts[, colnames(luad_adjusted_counts) %in% metadata$barcode]
mirna_subtype_acc <- sapply(1:ntrials, function(i) buildMultinomialGlm(metadata, counts, "subtype", mirnas))
tsrna_subtype_acc <- sapply(1:ntrials, function(i) buildMultinomialGlm(metadata, counts, "subtype", tsrnas))
snorna_subtype_acc <- sapply(1:ntrials, function(i) buildMultinomialGlm(metadata, counts, "subtype", mirnas))
permuted_subtype_acc <- sapply(1:ntrials, function(i) buildMultinomialGlm(metadata, counts, "subtype", tsrnas, randomize = TRUE))
```

```{r plot-subtype-accuracy, fig.width=8, fig.height=5}
df <- data.frame(tsRNA = tsrna_subtype_acc, miRNA = mirna_subtype_acc, snoRNA = snorna_subtype_acc, Permuted = permuted_subtype_acc)
df <- melt(df)
colnames(df) <- c("Features", "Accuracy")
ggplot(df) + geom_boxplot(aes(x = Features, y = Accuracy, color = Features))
```



```{r save-session, eval=FALSE}
save.session("predict-subtype.RSession")
```
